version: '3.9'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO__USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO__PASSWORD
      MONGO_INITDB_DATABASE: pulse
    volumes:
      - ./data/mongo:/data/db:rw
    expose:
      - 27017
    ports:
      - "6000:27017"
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/pulse --quiet
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: $MI__USERNAME
      MINIO_ROOT_PASSWORD: $MI__PASSWORD
    volumes:
      - ./data/minio/data:/data:rw
      - ./data/minio/config:/root/.minio:rw
    command: server /data/ --console-address ":9001"
    expose:
      - 9000
      - 9001
    ports:
      - "6002:9000"
      - "6003:9001"
    restart: unless-stopped
    healthcheck:
      test: curl -f http://minio:9000/minio/health/live
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m

  server:
    image: "ghcr.io/osu-pulse/osu-pulse-server:${VERSION__SERVER}"
    environment:
      CORS: true
      DEBUG: true
      URL_API: "http://${DEPLOY__HOST}/api"
      URL_AUTH: "http://${DEPLOY__HOST}/auth"
      URL_CLIENT: "http://${DEPLOY__HOST}"
      URL_MINIO: "http://${DEPLOY__HOST}/minio"
      URL_OSU: "http://${DEPLOY__HOST}/osu"
      DB_ENDPOINT: mongo
      DB_PORT: 27017
      DB_NAME: pulse
      DB_USERNAME: $MONGO__USERNAME
      DB_PASSWORD: $MONGO__PASSWORD
      MI_ENDPOINT: minio
      MI_PORT: 9000
      MI_USERNAME: $MI__USERNAME
      MI_PASSWORD: $MI__PASSWORD
      OSU_CLIENT_ID: $OSU__CLIENT_ID
      OSU_CLIENT_SECRET: $OSU__CLIENT_SECRET
    expose:
      - 5000
    ports:
      - "6004:5000"
    depends_on:
      - mongo
      - minio
    restart: unless-stopped
    healthcheck:
      test: curl -f http://server:5000/health
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m

  client:
    image: "ghcr.io/osu-pulse/osu-pulse-client:${VERSION__CLIENT}"
    expose:
      - 8080
    ports:
      - "6005:8080"
    restart: unless-stopped
    healthcheck:
      test: curl -f http://client:80
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m

  nginx:
    image: nginx:alpine
    expose:
      - 80
    ports:
      - "6006:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: curl -f http://nginx:80/health
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m

  caddy:
    image: caddy:alpine
    expose:
      - 80
    ports:
      - "6007:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy/data:/data:rw
    networks:
      - caddy
    restart: unless-stopped
    healthcheck:
      test: curl -f http://caddy:80/health
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m

networks:
  caddy:
    external: true
